Add PULL_REQUEST_TEMPLATE
grote/Transportr pull request #875
Opened 2023-07-30 16:48 UTC by pt2121

Hope this would help our code review process

2023-08-13 19:09 UTC, ialokim commented
There is already a PR template for releases in `.github/PULL_REQUEST_TEMPLATE/release.md`. How would they play together? Maybe this one should be moved to the same folder and given a different name?

2023-08-13 19:16 UTC, ialokim requested changes

2023-08-13 19:16 UTC, ialokim commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `connectedCheck` passes
What do you mean by `connectedCheck`? Maybe some further explanation would be nice.

2023-08-13 19:16 UTC, ialokim commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Changes has been tested on an Android device or Android emulator with API 21
Maybe also add a checkbox that says the Gradle `automatedTest`s have been checked to succeed.

2023-08-19 23:29 UTC, pt2121 commented
> There is already a PR template for releases in .github/PULL_REQUEST_TEMPLATE/release.md

That one didn't show up for me. I guess I have to pass the query param for the template.
Anyway, I will look into this later when I have time. Closing it now.

2023-08-19 23:29 UTC, closed without merging