Fix location provider
grote/Transportr pull request #912
Opened 2024-01-11 13:32 UTC by Altonss

This is a quick fix that should close #911.
@Kelvino9 @licaon-kter could you try it out?

2024-01-11 14:26 UTC, licaon-kter commented
rebuilt and confirm that it fixes the issue, no crash

2024-01-11 14:51 UTC, Kelvino9 commented
Thank you @Altonss for the fix and @licaon-kter for providing an APK.

Transportr does not crash upon start with this build, but also no longer is able to get a fix on my positon like in previous releases. Is there no way to get that function back? 

I do not depend on this functionality as I can use any navigation app to get more information on my surroundings on an unknown area, but it would be a nice to have feature since it was successfully included before.

Thanks anyway for the immediate bug fix.

2024-01-11 15:03 UTC, licaon-kter commented
@Kelvino9 so you say that if you lock GPS location in GPSTest app, and then you open this app, it won't get your location?

Works fine for me here.

2024-01-11 15:33 UTC, Kelvino9 commented
@licaon-kter I deleted everything, rebooted and tested again. It seems to work as intended after waiting for a few moments.

I did install GPSTest this time, because you mentioned it above. It worked. I then uninstalled GPSTest and reinitialized Transportr and it again worked as intended. I hope there isn't any data left from GPSTest and Transportr will continue to work without the need of running GPSTest before.

Was I just impatient when trying to get a fix on my position in Trasnportr? I didn't got a warning from Transportr earlier that it couldn't retrieve my position yet, but it notified me in later tests which actually led me to wait a bit.

2024-01-11 16:01 UTC, licaon-kter commented
GPS takes time to get a lock, I guess this app needs a bigger icon for _"looking for location"_ :)

2024-01-11 22:27 UTC, ialokim requested changes
Thanks @Altonss for the quick investigation and fix! I've looked into the `PositionController` again and also found the for-loop in `onInactive()` to be useless. Maybe you can remove that too in this PR.

2024-01-11 22:27 UTC, ialokim commented on app/src/main/java/de/grobox/transportr/map/PositionController.kt
>          for (provider in LOCATION_PROVIDERS) {
```suggestion
        for (provider in LOCATION_PROVIDERS.filter(locationManager::isProviderEnabled)) {
```
and remove the extra if-statement and indentation. Slightly more idiomatic I'd say.

2024-01-11 23:01 UTC, ialokim commented on app/src/main/java/de/grobox/transportr/map/PositionController.kt
>          for (provider in LOCATION_PROVIDERS) {
And the extra private fun, obviously.

2024-01-12 16:16 UTC, Kelvino9 commented
In Organics Maps you'll be notified to change location permission manually once you denied location permission.

2024-01-13 14:32 UTC, ialokim commented
> Only little issue I have, but idk if it's supposed to be normal, is that Transportr never asks me again about the location permission once I refuse (even if I click on the grey locate button).

Good remark, let's follow up on this in #916 .

2024-01-13 14:32 UTC, ialokim approved these changes
Thanks!

2024-01-13 14:33 UTC, merged